path:
  data_path: '../data/cifar-10/'
  result_path: results/VIT_cifar10/
  config_path: config/CIFAR10/config.yaml

general:
  num_classes: 10
  num_per_class: 10

vit_learning:
  train_batch_size: 10
  test_batch_size: 10
  num_workers: 4
  learning_rate: 0.001
  momentum: 0.9
  decrease_lr_factor: 0.1
  decrease_lr_every: 30
  epochs: 1

attack_learning:
  train_batch_size: 10
  test_batch_size: 10
  num_workers: 4
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.001
  decrease_lr_factor: 0.1
  decrease_lr_every: 30
  epochs: 1
